/**
 * @file Event.js
 * @description Mongoose model for tracking events.
 *
 * Each document represents a single user interaction (page_view or click)
 * captured by the SessionPulse tracking script.
 */

const mongoose = require('mongoose');

/**
 * @typedef {Object} EventDocument
 * @property {string}   session_id  - Unique session identifier (from localStorage)
 * @property {string}   event_type  - Type of event: 'page_view' | 'click'
 * @property {string}   page_url    - Full URL of the page where the event occurred
 * @property {Date}     timestamp   - When the event happened (client-side time)
 * @property {number}   [x]         - Horizontal click coordinate in pixels
 * @property {number}   [y]         - Vertical click coordinate in pixels
 * @property {Date}     createdAt   - Server-side insertion time (auto)
 */
const eventSchema = new mongoose.Schema(
  {
    /**
     * Session identifier generated by the tracking script and persisted
     * in localStorage. Allows grouping events from the same browsing session.
     */
    session_id: {
      type: String,
      required: [true, 'session_id is required'],
      trim: true,
      index: true, // ← fast session lookups
    },

    /**
     * The type of user interaction.
     * Only 'page_view' and 'click' are accepted — anything else is rejected.
     */
    event_type: {
      type: String,
      required: [true, 'event_type is required'],
      enum: {
        values: ['page_view', 'click'],
        message: "event_type must be 'page_view' or 'click'",
      },
      index: true, // ← filter by event type (e.g. heatmap only needs 'click')
    },

    /**
     * Full URL of the page where the event occurred.
     * Used for per-page analytics and heatmap filtering.
     */
    page_url: {
      type: String,
      required: [true, 'page_url is required'],
      trim: true,
      index: true, // ← heatmap queries filter by page_url
    },

    /**
     * Client-side timestamp of the event.
     * We store this (not just createdAt) because network latency can
     * cause significant delay between the event and its server arrival.
     */
    timestamp: {
      type: Date,
      required: [true, 'timestamp is required'],
      index: true, // ← used in time-range queries and session ordering
    },

    /**
     * Horizontal pixel coordinate of a click event.
     * Only populated when event_type === 'click'.
     */
    x: {
      type: Number,
      default: null,
    },

    /**
     * Vertical pixel coordinate of a click event.
     * Only populated when event_type === 'click'.
     */
    y: {
      type: Number,
      default: null,
    },
  },
  {
    /**
     * Adds createdAt and updatedAt fields automatically.
     * createdAt = server-side insertion time (useful for auditing).
     */
    timestamps: true,

    /**
     * Disables the __v (version key) field — not needed for this schema.
     */
    versionKey: false,
  }
);

// ── Compound Indexes ──────────────────────────────────────────────────────────

/**
 * Compound index on (session_id, timestamp).
 * Optimises the "get all events for a session ordered by time" query.
 */
eventSchema.index({ session_id: 1, timestamp: 1 });

/**
 * Compound index on (page_url, event_type).
 * Optimises the heatmap query that filters by page AND event type.
 */
eventSchema.index({ page_url: 1, event_type: 1 });

// ── Model ─────────────────────────────────────────────────────────────────────

const Event = mongoose.model('Event', eventSchema);

module.exports = Event;
